
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: apartment-service
          uri: http://localhost:8909
          predicates:
            - Path=/api/apartments/**
        - id: resident-service
          uri: http://localhost:8908
          predicates:
            - Path=/api/residents/**
